POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
GET http://localhost:8080/auth/logout


###
POST http://localhost:8080/transport/routes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTczOTY5ODczM30.fjTUb8JSNBTRWpLrUBJBVLesDLeIL17zFlMDs2WfCzQ

{
  "number": "102",
  "directions": [
    {
      "name": "LTU - Studentski Grad",
      "startTime": "04:30",
      "endTime": "21:55",
      "interval": "18",
      "stops": [
        { "name": "LTU" },
        { "name": "ZH. K. Darvenitsa" },
        { "name": "Unss" },
        { "name": "Detski Dom" },
        { "name": "Sportna Zala HR. Botev" },
        { "name": "Detski Yasli" },
        { "name": "Zimen Dvorets Na Sporta" },
        { "name": "SK Na NSA" },
        { "name": "Studentski Grad" }
      ]
    },
    {
      "name":"Studentski Grad - LTU",
      "startTime": "04:50",
      "endTime": "22:15",
      "interval": "10",
      "stops": [
        { "name": "Studentski Grad" },
        { "name": "SK Na NSA" },
        { "name": "Zimen Dvorets Na Sporta" },
        { "name": "Detski Yasli" },
        { "name": "Sportna Zala HR. Botev" },
        { "name": "Detski Dom" },
        { "name": "Unss" },
        { "name": "ZH. K. Darvenitsa" },
        { "name": "LTU" }
      ]
    }
  ]
}

###
GET http://localhost:8080/transport/routes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTczOTY2MTA1NX0.NssWMEIQ0HQqF0T2Z6AezqScX1lCaE21sUEOMaeuNAs

{
  "stopName": "Studentski Grad"
}

###
GET http://localhost:8080/transport/routes/280/schedule
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTczOTY1NTgxN30.oqfGtQVH0eNOvgybbnSgsyFJ92C1D8Y7JJz35Vsr0y4

###
GET http://localhost:8080/transport/stops
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTczOTY4MTIxOH0.jIc5sLWVboyMkyecxlEji3dEekotYKp_Nmno1y1txyQ